### ISSUE TITLE
Specifics for debugging: Cannot use 'in' operator to search for 'attachments' in undefined

### ISSUE THREAD

**Issue by hwaseem04** [Aathish04/moodlearchiver#1]
I tried using my SNU moodle account to fetch documents. But I am prompted with the following error.
<p align="center">
  <img src="https://user-images.githubusercontent.com/85298297/222878565-e3ee3b2c-8cc1-4a5c-8188-408ac83a04f4.jpeg" width="350" alt="accessibility text">
</p>

I used this URL: https://lms.snuchennai.edu.in/ after selecting Custom backend

**Comment by Aathish04** [comment]
This should be fixed now - It was caused by minor differences in the LMS systems of SSN and SNU.

Check now, and do let me know if it persists, and feel free this issue if it doesn't!

**Comment by hwaseem04** [comment]
Awesome, It works.
I am closing this issue.
