### ISSUE TITLE
Service Not Available - Custom backEnd

### ISSUE THREAD

**Issue by gersontk777** [Aathish04/moodlearchiver#3]
Hello friend, good evening.

I was very happy to see your message on REDDIT, about your project to download entire MOODLE courses.

However, I was unable to connect, even though the server (https://moodle-ead.unipampa.edu.br) and course are available online.

I am attaching the error message.

If you can help me, I would be very grateful.

Congratulations on the project!

Regards.

Gerson..

**Comment by Aathish04** [comment]
Hello! Thanks for reporting this issue. Unfortunately, I can't see any error messages attached in this comment, so I can't really debug the tool without further information!
