### ISSUE TITLE
CORS missing allow header in Firefox

### ISSUE THREAD

**Issue by ppranav06** [Aathish04/moodlearchiver#4]
Hello, 

This tool never works in FIrefox, no matter Windows or Linux. Whenever I try logging in, I get an error stating `NetworkError when attempting to fetch resource.`

Getting into the developer console reveals the error message to be `CORS Missing Allow Headers`. Here is a screenshot.

![image](https://github.com/user-attachments/assets/049b44a4-ad65-4377-a916-7ff6ebbee75a)

This tool works perfectly in a chromium browser I tried within WSL. It can access and download all my course materials. 

Will it be possible to investigate into this issue? I can provide support regarding this anytime possible. 

Helpful files:
---

1. Returned JSON upon error:
```json
{
  "error": "A required parameter (username) was missing",
  "errorcode": "missingparam",
  "stacktrace": "* line 610 of /lib/moodlelib.php: moodle_exception thrown\n* line 45 of /login/token.php: call to required_param()\n",
  "debuginfo": "\nError code: missingparam",
  "reproductionlink": "https://lms.ssn.edu.in/"
}
```
2. Resopnse Headers
```headers
HTTP/1.1 200 OK
Date: Sun, 27 Oct 2024 04:39:06 GMT
Server: Apache
X-Powered-By: PHP/8.1.29
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 20 Aug 1969 09:23:00 GMT
Last-Modified: Sun, 27 Oct 2024 04:39:06 GMT
Accept-Ranges: none
Content-Length: 307
Connection: close
Content-Type: application/json; charset=utf-8
```
3. Request Headers
```
OPTIONS //login/token.php HTTP/1.1
Host: lms.ssn.edu.in
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Access-Control-Request-Method: POST
Access-Control-Request-Headers: user-agent
Referer: https://aathish04.github.io/
Origin: https://aathish04.github.io
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Priority: u=4
```

P.S. This project has saved me a lot of time. Cheers!

**Comment by TotalyEnglizLitrate** [comment]
Fixed it :) waiting on the PR to be merged

**Comment by ppranav06** [comment]
Totally works now. Thanks @TotalyEnglizLitrate!
